apiVersion: "v1"
kind: "Template"
metadata:
  name: "container-index-seed-pipeline"
objects:
  - apiVersion: "v1"
    kind: "BuildConfig"
    metadata:
        name: seed-job
    spec:
      source:
        type: Git
        git:
          uri: ${CONTAINER_INDEX_REPO}
          ref: ${CONTAINER_INDEX_BRANCH}
        contextDir: "seed-job"
      strategy:
        type: "JenkinsPipeline"
        jenkinsPipelineStrategy:
          jenkinsfile: |
            properties([
                pipelineTriggers([
                    pollSCM('H/10 * * * *')
                ])
            ])
            podTemplate(
                cloud: 'openshift',
                name: 'ccp-pipeline',
                label: 'ccp-pipeline',
                serviceAccount: 'jenkins',
                containers: [
                  containerTemplate(
                    name: 'jnlp',
                    image: '${CCP_OPENSHIFT_SLAVE_IMAGE}',
                    ttyEnabled: true,
                    alwaysPullImage: true,
                    workingDir: '/tmp',
                    privileged: true,
                    args: '${computer.jnlpmac} ${computer.name}'
                  )
                ],
            )
            {
                node ('ccp-pipeline'){
                    stage('Checkout Sources') {
                        dir("${CONTAINER_INDEX_DIR}") {
                            git url: '${CONTAINER_INDEX_REPO}', branch: '${CONTAINER_INDEX_BRANCH}'
                        }
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: "${PIPELINE_BRANCH}"]],
                            doGenerateSubmoduleConfigurations: false,
                            extensions: [
                                [$class: 'RelativeTargetDirectory', relativeTargetDir: "${PIPELINE_REPO_DIR}"],
                                [$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true, timeout: 10]
                            ],
                            submoduleCfg: [],
                            userRemoteConfigs: [
                                [url: "${PIPELINE_REPO}",refspec: '+refs/pull/*:refs/remotes/origin/pr/*']
                            ]

                        ])
                    }
                    stage('Parse index') {
                        dir("${PIPELINE_REPO_DIR}") {
                            sh "PYTHONPATH=${PIPELINE_REPO_DIR} python ccp/index_reader.py ${CONTAINER_INDEX_DIR}/index.d ${REGISTRY_URL} ${NAMESPACE} ${FROM_ADDRESS} ${SMTP_SERVER} ${CCP_OPENSHIFT_SLAVE_IMAGE}"
                        }
                    }
                }
            }
          env:
          - name: CONTAINER_INDEX_REPO
            value: ${CONTAINER_INDEX_REPO}
          - name: CONTAINER_INDEX_BRANCH
            value: ${CONTAINER_INDEX_BRANCH}
          - name: REGISTRY_URL
            value: ${REGISTRY_URL}
          - name: PIPELINE_REPO_DIR
            value: ${PIPELINE_REPO_DIR}
          - name: NAMESPACE
            value: ${NAMESPACE}
      triggers:
          - type: ConfigChange
parameters:
- description: URL of the registry to which image is to be pushed
  name: REGISTRY_URL
  displayName: Registry URL
- description: "Container Index to use"
  displayName: Container Index
  name: CONTAINER_INDEX_REPO
  required: true
  value: https://github.com/dharmit/ccp-openshift-index
- description: "Container Index branch to use"
  displayName: Container Index branch
  name: CONTAINER_INDEX_BRANCH
  required: true
  value: master
- description: Directory where Pipeline service code is present in slave container
  displayName: Pipeline repo directory
  name: PIPELINE_REPO_DIR
  required: true
  value: /opt/ccp-openshift
- description: Directory where container index is to be cloned
  displayName: Container index directory
  name: CONTAINER_INDEX_DIR
  required: true
  value: /tmp/container-index
- description: Namespace to which the resulting Jenkins Pipelines should belong
  displayName: OpenShift namespace
  name: NAMESPACE
  required: true
- description: From address to be used when sending email
  displayName: From email address
  name: FROM_ADDRESS
  required: true
- description: SMTP server to use to send emails
  displayName: SMTP server address
  name: SMTP_SERVER
  required: true
- description: ccp-openshift-slave container image name (with registry name)
  displayName: ccp-openshift-slave container image
  name: CCP_OPENSHIFT_SLAVE_IMAGE
  required: true
  value: registry.centos.org/pipeline-images/ccp-openshift-slave:latest
